### ISSUE TITLE
Sem solução

### ISSUE THREAD

**Issue by andrelucax** [projeto-de-algoritmos/graph-1-youssef-roger#1]
Joguei por bastante tempo e não consegui encontrar nenhuma solução, seria bom se o jogo fosse possível de ser completado!

**Comment by lievertom** [comment]
também não consegui ganhar, mesmo não jogando.

**Comment by youssef-md** [comment]
Caros usuários, a Master foi atualizada com a nova versão do jogo que possibilita você enfrentar o próprio algoritmo de bfs e tentar resolver seu tabuleiro o quanto antes possível
